### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Insert car image
- [x] Make the background green.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary..
- [x] Test all functionality again.
