### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] Listen for 'keydown' events on the document.
   - [x] If right arrow key is pressed, position the car right 90 deg.
   - [x]  If left arrow key is pressed, position the car left 90 deg.
   - [x] Update the car direction after each left or right arrow click.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Remove all commented code.
- [x] Test all functionality again.
