### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Position the car relative to top and left
- [x] Create a data model and add a location that will hold the car's x and y coordinates on the page.
- [x] Create a function that will make the car move every 16 milliseconds.
- [x] Use style property to set the inline style of the element.
- [x] Add an event listener to the document and listen to spacebar keydown event.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
