### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started.
- [x] Change the event listener to check for the condition of the car have being started.
- [x] Update the function so that the car stops if the users presses space again.
- [x] Clear out commented code.
- [x] Test the app on the browser one more time.
